@startuml TimeMagicLoop
!theme cerulean
skinparam backgroundColor White
title TimeMagicLoop

start

partition Avalanche {
repeat :[[https://traderjoexyz.com/ Buy]] **$TIME**; 
    :[[https://app.wonderland.money/#/stake Stake]] **$TIME**;
    floating note right: <i>~65,000% APY</i>
    :[[https://abracadabra.money/pool/2 Wrap]] **$MEMO**;
note right: Receive **$wMEMO**
repeat while (**$MIM** available to borrow using \n \t **$wMEMO** as collateral?) is (yes) not (no) ->
}

:[[https://anyswap.exchange/#/router Bridge]] **wMEMO** to the Fantom chain;

partition FTM
:Stake **$wMEMO** on [[https://morpheusswap.app/pools Morpheous Swap]];
floating note right: <i>~25% APR</i> \n <i>2% Deposit Fee</i>
if (**$MORPH** rewards available for harvest?) then (yes)
    :Harvest **$MORPH**;
    :Stake **$MORPH**; 
    floating note right: <i>~215% APR</i> \n <i>0% Deposit Fee</i>
else (no)
endif
}

end
@enduml